//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Przychodnia_rejestracja
{
    using System;
    using System.Collections.Generic;
    
    public partial class Choroby
    {
        public Choroby()
        {
            this.Diagnozy = new HashSet<Diagnozy>();
        }
    
        public int ID_Choroby { get; set; }
        public string nazwa { get; set; }
        public string opis { get; set; }
    
        public virtual ICollection<Diagnozy> Diagnozy { get; set; }
    }
}
