//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Przychodnia_rejestracja
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnozy
    {
        public int ID_Diagnozy { get; set; }
        public int ID_Choroby { get; set; }
        public int ID_Wizyty { get; set; }
        public string uwagi { get; set; }
    
        public virtual Choroby Choroby { get; set; }
        public virtual Wizyty Wizyty { get; set; }
    }
}
