//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Przychodnia_rejestracja
{
    using System;
    using System.Collections.Generic;
    
    public partial class LekarzSpecjalnosc
    {
        public int ID_LekarzSpecjalnosc { get; set; }
        public int ID_Lekarza { get; set; }
        public int ID_Specjalnosci { get; set; }
        public Nullable<System.DateTime> data_nadania { get; set; }
    
        public virtual Lekarze Lekarze { get; set; }
        public virtual Specjalnosci Specjalnosci { get; set; }
    }
}
