//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Przychodnia_rejestracja
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lekarstwa
    {
        public Lekarstwa()
        {
            this.Recepty1 = new HashSet<Recepty>();
        }
    
        public int ID_Lekarstwa { get; set; }
        public string nazwa { get; set; }
        public Nullable<double> cena { get; set; }
        public string ulotka { get; set; }
    
        public virtual Recepty Recepty { get; set; }
        public virtual ICollection<Recepty> Recepty1 { get; set; }
    }
}
