//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Przychodnia_rejestracja
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PrzychodniaEntities : DbContext
    {
        public PrzychodniaEntities()
            : base("name=PrzychodniaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Badania> Badanias { get; set; }
        public DbSet<Choroby> Chorobies { get; set; }
        public DbSet<Diagnozy> Diagnozies { get; set; }
        public DbSet<Lekarstwa> Lekarstwas { get; set; }
        public DbSet<Lekarze> Lekarzes { get; set; }
        public DbSet<LekarzSpecjalnosc> LekarzSpecjalnoscs { get; set; }
        public DbSet<Pacjenci> Pacjencis { get; set; }
        public DbSet<Recepty> Recepties { get; set; }
        public DbSet<Specjalnosci> Specjalnoscis { get; set; }
        public DbSet<Swiadczenia> Swiadczenias { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Wizyty> Wizyties { get; set; }
    }
}
