//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Przychodnia_rejestracja
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specjalnosci
    {
        public Specjalnosci()
        {
            this.LekarzSpecjalnoscs = new HashSet<LekarzSpecjalnosc>();
        }
    
        public int ID_Specjalnosci { get; set; }
        public string nazwa { get; set; }
    
        public virtual ICollection<LekarzSpecjalnosc> LekarzSpecjalnoscs { get; set; }
    }
}
